gameservers:
  fs25:
    enabled: true
    install_dir: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Farming Simulator 25"
    user: "admin"
    credential_name: "FS25Service"
    backup:
      retention_days: 7
    monitoring:
      enabled: true
      cpu_alert: 90
      ram_alert: 85
      discord_webhook: ""

    instances:
      - name: "vanilla"
        service_name: "FS25-Vanilla"
        port: 10823
        session_name: "Petit_Champ_du_Saguenay"
        max_players: 4
        map: "Zielonka"
        mods: []           # pas de mods pour vanilla

      - name: "modded"
        service_name: "FS25-Modded"
        port: 10824
        session_name: "Champ_de_la_Devastation"
        max_players: 5
        map: "ModdedMap"
        mods:
          - "Mod_ExtraTractors"  # mettre le nom du zip de la mod / ou des mods en ajoutant des - a la suite des autres
