# ===============================================
# ARK Survival Ascended
# ===============================================
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

#------ Variables ARK ------------
ENV ARK_USER=ark \
    ARK_HOME= /opt/ark \
    STEAMCMD_DIR=/opt/steamcmd \
    STEAMCMD_APP_ID=2430930

#------ Dépendances Système -------
RUN apt-get update && apt-get install -y \
    lib32gcc-s1 \
    lib32stdc++6 \
    ca-certificates \
    curl \
    tar \
    tzdata \
&& rm -rf /var/lib/apt/lists/*

#--- Création utilisateur ----------
RUN useradd -m -r -s /bin/bash ${ARK_USER}

#-------- SteamCMD -----------------
RUN mkdir -p ${STEAMCMD_DIR} && \
    curl -sL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz \
    | tar -xz -C ${STEAMCMD_DIR}


#------------ Dossier ARK -----------
RUN mkdir -p ${ARK_HOME} && \
    chown -R ${ARK_USER}:${ARK_USER} ${ARK_HOME} ${STEAMCMD_DIR}

USER ${ARK_USER}
WORKDIR ${ARK_HOME}

# ---- Installation ARK ASA -----------
RUN ${STEAMCMD_DIR}/steamcmd.sh \
    +login anonymous \
    +force_install_dir ${ARK_HOME} \
    +app_update ${STEAMCMD_APP_ID} validate \
    +quit 

# -------- Volume persistants ---------
VOLUME [
    "/opt/ark/ShooterGame/Saved",
    "/opt/ark/ShooterGame/Config",
    "opt/ark-backups"
]


#-----Ports ARK ------------------------
EXPOSE 7777/udp 27015/udp 27020/tcp


#-------- Start script ------------------
COPY .github/ark/start_ark.sh /usr/local/bin/start_ark.sh
RUN chmod +x /usr/local/bin/start_ark.sh

ENTRYPOINT [ "/usr/local/bin/start_ark.sh" ]